#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/group/xrlabs/phartke/bluetooth/nexys2/nexys2/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /build/xfndry/EDK_L.29.1/rtf
NON_CYG_XILINX_EDK_DIR = /build/xfndry/EDK_L.29.1/rtf

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan3e

DEVICE = xc3s500efg320-4

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst \
                   $(MICROBLAZE_0_LIBG_OPT)

OBSERVE_PAR_OPTIONS = -error yes

TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT_DIR = TestApp_Memory_microblaze_0
TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT = $(TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT_DIR)/executable.elf

TESTAPP_PERIPHERAL_MICROBLAZE_0_OUTPUT_DIR = TestApp_Peripheral_microblaze_0
TESTAPP_PERIPHERAL_MICROBLAZE_0_OUTPUT = $(TESTAPP_PERIPHERAL_MICROBLAZE_0_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT) 

ALL_USER_ELF_FILES = $(TESTAPP_MEMORY_MICROBLAZE_0_OUTPUT) $(TESTAPP_PERIPHERAL_MICROBLAZE_0_OUTPUT) 

SIM_CMD = 

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed no

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -sd implementation/


LIBRARIES =  \
       microblaze_0/lib/libxil.a 

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = TestApp_Memory_microblaze_0_programclean TestApp_Peripheral_microblaze_0_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/led_7segment_wrapper.ngc \
implementation/push_buttons_3bit_wrapper.ngc \
implementation/switches_8bit_wrapper.ngc \
implementation/rs232_port_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/mdm_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/chipscope_vio_0_wrapper.ngc \
implementation/chipscope_icon_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION TESTAPP_MEMORY_MICROBLAZE_0
#################################################################

TESTAPP_MEMORY_MICROBLAZE_0_SOURCES = TestApp_Memory_microblaze_0/src/TestApp_Memory.c 

TESTAPP_MEMORY_MICROBLAZE_0_HEADERS = 

TESTAPP_MEMORY_MICROBLAZE_0_CC = mb-gcc
TESTAPP_MEMORY_MICROBLAZE_0_CC_SIZE = mb-size
TESTAPP_MEMORY_MICROBLAZE_0_CC_OPT = -O2
TESTAPP_MEMORY_MICROBLAZE_0_CFLAGS = 
TESTAPP_MEMORY_MICROBLAZE_0_CC_SEARCH = # -B
TESTAPP_MEMORY_MICROBLAZE_0_LIBPATH = -L./microblaze_0/lib/ # -L
TESTAPP_MEMORY_MICROBLAZE_0_INCLUDES = -I./microblaze_0/include/ # -I
TESTAPP_MEMORY_MICROBLAZE_0_LFLAGS = # -l
TESTAPP_MEMORY_MICROBLAZE_0_LINKER_SCRIPT = TestApp_Memory_microblaze_0/src/TestApp_Memory_LinkScr.ld
TESTAPP_MEMORY_MICROBLAZE_0_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_MEMORY_MICROBLAZE_0_LINKER_SCRIPT) 
TESTAPP_MEMORY_MICROBLAZE_0_CC_DEBUG_FLAG =  -g 
TESTAPP_MEMORY_MICROBLAZE_0_CC_PROFILE_FLAG = # -pg
TESTAPP_MEMORY_MICROBLAZE_0_CC_GLOBPTR_FLAG= # -mxl-gp-opt
TESTAPP_MEMORY_MICROBLAZE_0_MODE = executable
TESTAPP_MEMORY_MICROBLAZE_0_LIBG_OPT = -$(TESTAPP_MEMORY_MICROBLAZE_0_MODE) microblaze_0
TESTAPP_MEMORY_MICROBLAZE_0_CC_INFERRED_FLAGS= -mxl-soft-mul -mxl-pattern-compare -mcpu=v7.20.a 
TESTAPP_MEMORY_MICROBLAZE_0_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
TESTAPP_MEMORY_MICROBLAZE_0_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_MEMORY_MICROBLAZE_0_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_MEMORY_MICROBLAZE_0_OTHER_CC_FLAGS= $(TESTAPP_MEMORY_MICROBLAZE_0_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_MEMORY_MICROBLAZE_0_CC_START_ADDR_FLAG) $(TESTAPP_MEMORY_MICROBLAZE_0_CC_STACK_SIZE_FLAG) $(TESTAPP_MEMORY_MICROBLAZE_0_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_MEMORY_MICROBLAZE_0_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_MEMORY_MICROBLAZE_0_LINKER_SCRIPT_FLAG) $(TESTAPP_MEMORY_MICROBLAZE_0_CC_DEBUG_FLAG) $(TESTAPP_MEMORY_MICROBLAZE_0_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION TESTAPP_PERIPHERAL_MICROBLAZE_0
#################################################################

TESTAPP_PERIPHERAL_MICROBLAZE_0_SOURCES = TestApp_Peripheral_microblaze_0/src/TestApp_Peripheral.c TestApp_Peripheral_microblaze_0/src/xgpio_tapp_example.c TestApp_Peripheral_microblaze_0/src/xuartlite_selftest_example.c 

TESTAPP_PERIPHERAL_MICROBLAZE_0_HEADERS = TestApp_Peripheral_microblaze_0/src/gpio_header.h TestApp_Peripheral_microblaze_0/src/uartlite_header.h 

TESTAPP_PERIPHERAL_MICROBLAZE_0_CC = mb-gcc
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_SIZE = mb-size
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_OPT = -O2
TESTAPP_PERIPHERAL_MICROBLAZE_0_CFLAGS = 
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_SEARCH = # -B
TESTAPP_PERIPHERAL_MICROBLAZE_0_LIBPATH = -L./microblaze_0/lib/ # -L
TESTAPP_PERIPHERAL_MICROBLAZE_0_INCLUDES = -I./microblaze_0/include/  -ITestApp_Peripheral_microblaze_0/src/ # -I
TESTAPP_PERIPHERAL_MICROBLAZE_0_LFLAGS = # -l
TESTAPP_PERIPHERAL_MICROBLAZE_0_LINKER_SCRIPT = TestApp_Peripheral_microblaze_0/src/TestApp_Peripheral_LinkScr.ld
TESTAPP_PERIPHERAL_MICROBLAZE_0_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_PERIPHERAL_MICROBLAZE_0_LINKER_SCRIPT) 
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_DEBUG_FLAG =  -g 
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_PROFILE_FLAG = # -pg
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_GLOBPTR_FLAG= # -mxl-gp-opt
TESTAPP_PERIPHERAL_MICROBLAZE_0_MODE = executable
TESTAPP_PERIPHERAL_MICROBLAZE_0_LIBG_OPT = -$(TESTAPP_PERIPHERAL_MICROBLAZE_0_MODE) microblaze_0
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_INFERRED_FLAGS= -mxl-soft-mul -mxl-pattern-compare -mcpu=v7.20.a 
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_PERIPHERAL_MICROBLAZE_0_OTHER_CC_FLAGS= $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_START_ADDR_FLAG) $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_STACK_SIZE_FLAG) $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_PERIPHERAL_MICROBLAZE_0_LINKER_SCRIPT_FLAG) $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_DEBUG_FLAG) $(TESTAPP_PERIPHERAL_MICROBLAZE_0_CC_PROFILE_FLAG) 
